kind: List
apiVersion: v1
items:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: shopping-list-deployment
      labels:
        app: shopping-list
      annotations:
        version: 0.0.1-SNAPSHOT
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: shopping-list
      template:
        metadata:
          labels:
            app: shopping-list
        spec:
          containers:
            - name: shopping-list
              image: shopping-list:0.0.1-SNAPSHOT
              args: ["--spring.profiles.active=hsqldb"]
              ports:
                - containerPort: 8080
                - containerPort: 8443
              lifecycle:
                preStop:
                  exec:
                    # SIGTERM triggers a quick exit; gracefully terminate instead
                    command: ["kill", "-SIGINT", "`pidof java`"]
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
              readinessProbe:
                httpGet:
                  path: /actuator/health
                  port: 8080
                initialDelaySeconds: 35
                timeoutSeconds: 1
                periodSeconds: 5
              livenessProbe:
                httpGet:
                  path: /actuator/health
                  port: 8080
                initialDelaySeconds: 40
                timeoutSeconds: 1
                periodSeconds: 5
  - kind: Service
    apiVersion: v1
    metadata:
      name: shopping-list-service
    spec:
      selector:
        app: shopping-list
      ports:
        - protocol: TCP
          name: http
          port: 80
          targetPort: 8080
        - protocol: TCP
          name: https
          port: 443
          targetPort: 8443
      type: NodePort
  - kind: Route
    apiVersion: v1
    metadata:
      name: shopping-list-route
    spec:
      host: shopping-list-myproject.192.168.64.9.nip.io
      port:
        targetPort: https
      tls:
        termination: passthrough
      to:
        kind: Service
        name: shopping-list-service